### PR TITLE
Add piramidka shell script

### PR DESCRIPTION
**Pull request by sbrych**
Moved piramidka script to shell script for easier use
lala
Inspired by PR by @tupaja (https://github.com/Adam-Stomski/szachmatkurwo/pull/1)

Example usage: piramidka 5

### CODE REVIEW

**Comment by Szeliga** [comment]
For the purpose of future development, I would like to have this script in a separate file, with a proper ruby shebang. This would allow us to have syntax highlighting. The alias would then run the script.

**Comment by Szeliga** [comment]
I don't speak bash

**Comment by Adam-Stomski** [comment]
tbh it's not an alias, how do you feel putting it into bin/ directory and make executable **piramidka** script? I have created a pr for ruby scripts included into single gem for easier updates https://github.com/Adam-Stomski/szachmatkurwo/pull/3

but I like this one so much, I'd like to have it in the repo for historical reasons, and future generations of szachmatkurwo may want to choose between bash scripts and ruby gem.

**Comment by Adam-Stomski** [comment]
also, I can imagine a situation when you don't have access to ruby but still want to use this beautiful script

**Pull request merged**
